services:

  postgres:
    image: postgres:latest
    container_name: db-container
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - app_network

  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link_shortener
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge